apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: onboarding
  name: onboarding
spec:
  replicas: 1
  selector:
    matchLabels:
      run: onboarding
  template:
    metadata:
      labels:
        run: onboarding
    spec:
      containers:
      - image: moscho/onboarding:v1
        name: onboarding
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: onboarding
  name: onboarding
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: onboarding
  type: LoadBalancer