name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build docker image
      run: docker build -t registry.ingress.oba.d052927.shoot.canary.k8s-hana.ondemand.com/onboarding:latest .

    - name: Login to Registry
      env: 
        REGISTRY_TOKEN: ${{secrets.REGISTRY_SECRET}}
      run: docker login -u participant -p $REGISTRY_TOKEN registry.ingress.oba.d052927.shoot.canary.k8s-hana.ondemand.com/
    
    - name: Push Image
      run: docker push registry.ingress.oba.d052927.shoot.canary.k8s-hana.ondemand.com/onboarding:latest
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: docker images