name: Test

on:
  issue_comment:
    types: [created, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'test'
    
    steps:
      - uses: actions/checkout@v2
        
      - name: private-action
        uses: cc-playground/docker-login-action@master
      - name: test
        run: |
          echo test-step
          ls
