name: Test

on:
  issue_comment:
    types: [created, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'test'
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/setup-kubectl@v1
      
      - name: test
        run: |
          kubectl config view
