name: Test

on:
  issue_comment:
    types: [created, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'test'
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/setup-kubectl@v1
      
      - name: test
        run: |
          kubectl config set-credentials admin --token=${{secrets.K8S_TOKEN}}
          kubectl config set-cluster cluster --server='https://api.oba.d052927.shoot.canary.k8s-hana.ondemand.com/' --insecure-skip-tls-verify=true
          kubectl config set-context admin-context --cluster=cluster --user=admin
          kubectl config use-context admin-context
          kubectl config view
          kubectl get nodes
