name: Test

on:
  issue_comment:
    types: [edited]

jobs:
  test-job:
    runs-on: ubuntu-latest
    if: github.event.comment.body == 'test'

    steps:
      - name: Hello world
        run: echo Hello world, I was run on demand by ${GITHUB_ACTOR}
